TASK 1:

Import the numpy library and check its version.

In [12]:
import numpy as np
# np.__version__

TASK 2:
Creating a NumPy Array:

In [2]:
# 1. Create a 1D NumPy array from a Python list

arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)


1D Array:
[1 2 3 4 5]


In [22]:
# 2. Create a 2D NumPy array of shape (3x3) using numbers 1 to 9
arr2 = np.random.randint(1,9 ,size = (3, 3))
print("2D Array:")
print(arr2)

2D Array:
[[2 6 3]
 [1 5 1]
 [8 3 3]]


In [10]:
# 3. Generate 10 evenly spaced values between 0 and 5
arr3 = np.linspace(0, 5,num= 10)
print("Evenly Spaced Array:")
print(arr3)

Evenly Spaced Array:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


TASK 3:
Indexing and Slicing Arrays:

In [ ]:
print("Original Array:")
print(arr2)

# 1. Access element in second row, third column

element = arr2[1:2, 2:]
print("\nElement at second row, third column:", element)


Original Array:
[[2 6 3]
 [1 5 1]
 [8 3 3]]

Element at second row, third column: [[1]]


In [24]:
# 2. Slice first two rows and first two columns

sliced_array = arr2[:2, :2]
print("First two rows and first two columns:")
print(sliced_array)

First two rows and first two columns:
[[2 6]
 [1 5]]


In [25]:
# 3. Modify last row, first column to 100

arr2[2, 0] = 100
print("\nModified Array:")
print(arr2)


Modified Array:
[[  2   6   3]
 [  1   5   1]
 [100   3   3]]


TASK 4:
Properties and Methods of NumPy Arrays

In [28]:
# 1. Find shape, size, and data type


print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)


Shape: (3, 3)
Size: 9
Data Type: int32


In [29]:
# 2. Change 1D array into 2D array of shape (5,1)

print(arr1)

arr1_2d = arr1.reshape(5, 1)

print("1D array reshaped to (5,1):")
print(arr1_2d)

[1 2 3 4 5]
1D array reshaped to (5,1):
[[1]
 [2]
 [3]
 [4]
 [5]]


In [31]:
# 3. Flatten multi-dimensional array into 1D array


flattened = arr2.flatten()

print("Flattened array:",flattened)


Flattened array: [  2   6   3   1   5   1 100   3   3]


TASK 5 :
Operations on NumPy Arrays

In [ ]:
# 1. Add 5 to every element in the 1D array

result1 = np.add(arr1,5)
print("1D array after adding 5:", result1)

1D array after adding 5: [ 6  7  8  9 10]


In [38]:
# 2. Multiply every element of the 2D array by 3

result2 = np.multiply(arr2,3)
print("2D array after multiplying by 3:")
print(result2)

2D array after multiplying by 3:
[[  6  18   9]
 [  3  15   3]
 [300   9   9]]


In [39]:
# 3. Matrix multiplication

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result3 = np.dot(A, B)

print("Matrix Multiplication:")
print(result3)

Matrix Multiplication:
[[19 22]
 [43 50]]


TASK 6:
Understanding Broadcasting

In [40]:
# Create a 3x3 matrix of ones
matrix = np.ones((3, 3))

# Create a 1D array of length 3
arr = np.array([1, 2, 3])

In [41]:
# Add the 1D array to each row using broadcasting

result = matrix + arr

print("Matrix of ones:")
print(matrix)

print("\n1D Array:")
print(arr)

print("\nResult after broadcasting:")
print(result)

Matrix of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D Array:
[1 2 3]

Result after broadcasting:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
