In [1]:
import numpy as np

a= np.random.randint(10,50, size=(5,2,3), dtype="int16")

In [2]:
a.shape

(5, 2, 3)

In [3]:
a.ndim

3

In [4]:
a.dtype

dtype('int16')

In [5]:
a.T

array([[[31, 32, 23, 25, 20],
        [36, 18, 37, 15, 12]],

       [[21, 38, 25, 31, 25],
        [11, 31, 10, 30, 47]],

       [[28, 27, 27, 40, 27],
        [23, 24, 13, 41, 20]]], dtype=int16)

In [6]:
a.size

30

In [8]:
a= np.random.randint(10,50, size=(5,4), dtype="int16")
a

array([[47, 45, 48, 12],
       [10, 31, 22, 39],
       [12, 32, 10, 41],
       [35, 46, 35, 44],
       [23, 49, 17, 12]], dtype=int16)

In [ ]:
b = a.reshape(5,2,-1) #<- -1: auto adjust
b

array([[[47, 45],
        [48, 12]],

       [[10, 31],
        [22, 39]],

       [[12, 32],
        [10, 41]],

       [[35, 46],
        [35, 44]],

       [[23, 49],
        [17, 12]]], dtype=int16)

In [11]:
a.flatten()  #a.ravel

array([47, 45, 48, 12, 10, 31, 22, 39, 12, 32, 10, 41, 35, 46, 35, 44, 23,
       49, 17, 12], dtype=int16)

In [12]:
a

array([[47, 45, 48, 12],
       [10, 31, 22, 39],
       [12, 32, 10, 41],
       [35, 46, 35, 44],
       [23, 49, 17, 12]], dtype=int16)

In [13]:
a.sum()

np.int64(610)

In [14]:
a.sum(axis=0) # column wise vertical

array([127, 203, 132, 148])

In [15]:
a.sum(axis = 1)  #row wise horizontal

array([152, 102,  95, 160, 101])

In [16]:
a.cumsum()

array([ 47,  92, 140, 152, 162, 193, 215, 254, 266, 298, 308, 349, 384,
       430, 465, 509, 532, 581, 598, 610])

In [17]:
a.cumprod(axis=1)

array([[     47,    2115,  101520, 1218240],
       [     10,     310,    6820,  265980],
       [     12,     384,    3840,  157440],
       [     35,    1610,   56350, 2479400],
       [     23,    1127,   19159,  229908]])

In [18]:
a

array([[47, 45, 48, 12],
       [10, 31, 22, 39],
       [12, 32, 10, 41],
       [35, 46, 35, 44],
       [23, 49, 17, 12]], dtype=int16)

In [19]:
a.argmax(axis=0)

array([0, 4, 0, 3])

In [20]:
a.clip(min= 20, max= 40)

array([[40, 40, 40, 20],
       [20, 31, 22, 39],
       [20, 32, 20, 40],
       [35, 40, 35, 40],
       [23, 40, 20, 20]], dtype=int16)

In [21]:
#Concatenation or Join

arr1= np.random.randint(1,100, size=(3,3))
arr2= np.random.randint(1,100, size=(3,3))

In [23]:
arr1, arr2

(array([[12, 19, 94],
        [12, 36, 59],
        [78, 23, 77]], dtype=int32),
 array([[83, 51, 60],
        [92, 46, 73],
        [64, 75, 12]], dtype=int32))

In [25]:
np.concatenate([arr1, arr2], axis =1)

array([[12, 19, 94, 83, 51, 60],
       [12, 36, 59, 92, 46, 73],
       [78, 23, 77, 64, 75, 12]], dtype=int32)

In [26]:
np.vstack([arr1, arr2])

array([[12, 19, 94],
       [12, 36, 59],
       [78, 23, 77],
       [83, 51, 60],
       [92, 46, 73],
       [64, 75, 12]], dtype=int32)

In [27]:
np.hstack([arr1, arr2])

array([[12, 19, 94, 83, 51, 60],
       [12, 36, 59, 92, 46, 73],
       [78, 23, 77, 64, 75, 12]], dtype=int32)